### ISSUE TITLE
3.3.5 表格与图报错了

### ISSUE THREAD

**Issue by englishyj** [sunshe35/PythonPlotlyCodes#3]
Traceback (most recent call last):
  File "D:/pywork/ploylytest/test004.py", line 53, in <module>
    figure['data'].extend(go.Data([trace1, trace2]))
AttributeError: 'tuple' object has no attribute 'extend'

figure 无法添加新元素？

**Comment by sunshe35** [comment]
版本错了，用2.0.0版本。



---原始邮件---
发件人: "凤翱"<notifications@github.com&gt;
发送时间: 2019年10月23日(星期三) 下午5:16
收件人: "sunshe35/PythonPlotlyCodes"<PythonPlotlyCodes@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [sunshe35/PythonPlotlyCodes] 3.3.5 表格与图报错了 (#3)



Traceback (most recent call last):
 File "D:/pywork/ploylytest/test004.py", line 53, in 
 figure['data'].extend(go.Data([trace1, trace2]))
 AttributeError: 'tuple' object has no attribute 'extend'
 
figure 无法添加新元素？
